### ISSUE TITLE
JSON Parent 

### ISSUE THREAD

**Issue by PoojaRohite** [open-source-parsers/jsoncpp#895] opened 2019-03-11 07:07 UTC
How to get parent object name while recursive call to process_value in order to populate values in different structures based on parent name. Example:
```js
{
  "Hdr" : {
       "PrtcolVrsn" : "V1.0"
      ,"CreDtTm" : "2019-03-04T12:12:12"
      ,"InitgPty" : {
        "Id" : "TYUI"
        ,"Tp" : "KLM"
      }
      ,"RcptPty" : {
        "Id" : "HJW"
        ,"Tp" : "CISP"
      }
  }
}
```
InitgPty and RcptPty .. there are two parent and have child names same but I need to populate their values based on parent name in different structure.

**Comment by PoojaRohite** [comment] 2019-03-11 07:20
- [ ] 
1. 
-

**Comment by PoojaRohite** [comment] 2019-03-11 08:53
Help needed

**Comment by dota17** [comment] 2019-05-16 04:58
Hi @PoojaRohite  In jsoncpp `name-value` pairs stored in `vector` container ,and in the ***writeValue*** function it works like:
1. `Value::Members members(value.getMemberNames());` 
2. `auto it = members.begin();`          //get a map's first element pointer
3. `const String& name = *it;`           //
so  we get parent object name, it's ok that there are two parent and have child names same.
`Json::Value root,item,item1,member;`
` item[Id]="TYUI";    item[Tp]="KLM";   `
` item1[Id]="HJW";  item1[Tp]="CISP";   `
` member[InitgPty]= item;`
`member[InitgPty]= item1;`
`member[PrtcolVrsn]="V1.0";`
`member[CreDtTm]="2019-03-04T12:12:12";`
`root[Hdr]=member;`
`std::string json = root.toStyledString();`

Hope it helps you.

**Comment by baylesj** [comment] 2019-06-28 17:06
Closing as not a bug or feature.

**Closed by baylesj** 2019-06-28 17:06 UTC
