### ISSUE TITLE
why have so more null value

### ISSUE THREAD

**Issue by myvcgit** [open-source-parsers/jsoncpp#1117] opened 2019-12-11 03:16 UTC
**Describe the bug**
the json file have so more null that is not need ,what happend 

this my code 

```
class A
{
public:
	int m_iIndex;
private:

};

class B
{
public:
	std::vector <A*> m_arryList;
	void WriteJsonData(int i);
private:

};

void B::WriteJsonData(int i)
{
	char filename[] = "w:/test.json";
	Json::Value root;
	std::ofstream os;
	os.open(filename, std::ios_base::out);
	root["log"]["loglevel"] = "warning";
	Json::Value j_in;
	Json::Value j_out;
	Json::Value j_filter_rules;
	j_in[i]["index"] = m_arryList.at(i)->m_iIndex;
	j_out[i]["count"]["enable"] = true;
	root["in"] = j_in;
	root["out"] = j_out;
	root["filter"]["rules"] = j_filter_rules;
	root["policy"];
	Json::Value j_other(Json::objectValue);
	root["other"] = j_other;
	os << root;
	os.close();
}

int main()
{
	B* pB = new B;
	for (int i = 0; i < 10; i++)
	{
		A* pA = new A;
		pA->m_iIndex = i;
		pB->m_arryList.push_back(pA);
	}
	pB->WriteJsonData(5);
}
`
this the test,json file value

{
	"filter" : 
	{
		"rules" : null
	},
	"in" : 
	[
		null,
		null,
		null,
		null,
		null,
		{
			"index" : 5
		}
	],
	"log" : 
	{
		"loglevel" : "warning"
	},
	"other" : {},
	"out" : 
	[
		null,
		null,
		null,
		null,
		null,
		{
			"count" : 
			{
				"enable" : true
			}
		}
	],
	"policy" : null
}
```

 that have 5 null the dont need 

what can I do to not generate that 5 null

**Comment by dota17** [comment] 2019-12-16 13:09
If you assign a value to a[5], Jsoncpp store the <5, value> in a map. When you output the array value, Jsoncpp will get the highest index +1(=6) as the size of array firstly.
https://github.com/open-source-parsers/jsoncpp/blob/d6c4a8fb2defc505d401d39097c00fdd8be9ae33/src/lib_json/json_writer.cpp#L725
https://github.com/open-source-parsers/jsoncpp/blob/d6c4a8fb2defc505d401d39097c00fdd8be9ae33/src/lib_json/json_value.cpp#L861
Then a[0]~a[4] will be initialized as null value when we access and output the array by for loop.
https://github.com/open-source-parsers/jsoncpp/blob/d6c4a8fb2defc505d401d39097c00fdd8be9ae33/src/lib_json/json_writer.cpp#L736
So we get the result with 5 null. You could not avoid generating 5 null.

**Comment by BillyDonahue** [comment] 2019-12-16 14:38
Not a bug.

Yes, the array is null-filled when it is autoextended.

**Closed by BillyDonahue** 2019-12-16 14:38 UTC
