### ISSUE TITLE
Possible to limit precision of number types?

### ISSUE THREAD

**Issue by richardeakin** [open-source-parsers/jsoncpp#284] opened 2015-05-29 20:05 UTC
I have a json-based config where I write some parameters, and when my application closes it uses the `Json::StyledWriter` to save the latest state of my root `Json::Value` object. I understand that round trip floating point precision isn't guarunteed to be exact, but is there a way to avoid numbers such as `0.15` being saved as `0.14999999999999999`? This makes the config file difficult to read.

One solution I was wondering about is whether I could limit the precision of floating point numbers, I rarely in this case want more than 4 significant decimals and that would at least improve the use case.

**Comment by cdunn2001** [comment] 2015-05-30 05:29
First, please use `StreamWriterBuilder`. That allows us to add extra configuration without breaking binary-compatibility.

Note that, as described in issue #98, you will not have round-trip reproducibility if you have fewer than 17 digits of precision. Despite that caveat, we could add a setting to limit the precision. However, I don't have time right now, but if you submit a PR, we could pull it.

**Comment by bknecht** [comment] 2015-08-14 11:25
I saw you just closed this issue I'm interested in. What's the resolution? I just had a quick look at the code of StreamWriterBuilder and I think it's not too difficult to do. Is your request for a PR still open? I'll sit down and have a try at it if you're still interested.

**Comment by cdunn2001** [comment] 2015-08-14 23:28
Great!

**Comment by Thuenem** [comment] 2015-08-14 23:45
I am out of the office until 25.08.2015.

Dear Business Partner, I will be out of the office starting 17.08.2015 and
will not return until 25.08.2015. Your message will not be processed during
my abscence. I will respond to your message when I return. In urgent cases
please contact Peter Winterberg under +49.5971.80819953 or mail
peter.winterberg@prognost.com. - Thank you.


Note: This is an automated response to your message  "Re: [jsoncpp]
Possible to limit precision of number types? (#284)" sent on 15.08.2015
01:28:21.

This is the only notification you will receive while this person is away.

**Comment by Thuenem** [comment] 2015-08-14 23:45
I am out of the office until 25.08.2015.

Dear Business Partner, I will be out of the office starting 17.08.2015 and
will not return until 25.08.2015. Your message will not be processed during
my abscence. I will respond to your message when I return. In urgent cases
please contact Peter Winterberg under +49.5971.80819953 or mail
peter.winterberg@prognost.com. - Thank you.


Note: This is an automated response to your message  "Re: [jsoncpp]
Possible to limit precision of number types? (#284)" sent on 15.08.2015
01:28:59.

This is the only notification you will receive while this person is away.

**Closed** 2015-10-15 21:15 UTC
Labels: enhancement

**Comment by longlene** [comment] 2016-04-26 09:29
I think the reason of this problem is that: jsoncpp library use the double type to present the float-point number. 
The double type use IEEE-754 standard, which may cause precision lose.

**Comment by cdunn2001** [comment] 2016-04-27 07:50
That makes sense. Thanks.

**Comment by shuhongwang-zzu** [comment] 2019-07-19 01:41
anyone help?

**Comment by dota17** [comment] 2019-07-19 03:24
> anyone help?

see the PR #381

**Comment by shuhongwang-zzu** [comment] 2019-07-19 05:42
> > anyone help?
> 
> see the PR #381
Maybe the version of jsoncpp is inconsistent, mine is
JSONCPP_STRING valueToString(double value,
                             unsigned int precision,
                             PrecisionType precisionType) {
  return valueToString(value, false, precision, precisionType);
}
can you help me again?
