### ISSUE TITLE
"Error: Cannot take the address of a bit field." compile error on Solaris 11 Sparc

### ISSUE THREAD

**Issue by punchkicker** [open-source-parsers/jsoncpp#479] opened 2016-05-26 03:17 UTC
Hello.

I am trying to compile my project on a Solaris 11.3 sparc sun4v server.  I am using the amalgamated source of Jsoncpp 1.7.2 (originally using v1.6.5, same error), with no changes.  During compilation, I am getting this error:

> "dist/jsoncpp.cpp", line 4630: Error: Cannot take the address of a bit field.

this line number maps to:

> (4629)  StyledStreamWriter::StyledStreamWriter(JSONCPP_STRING indentation)
> (**4630**)     : document_(NULL), rightMargin_(74), indentation_(indentation),
> (4631)        addChildValues_() {}

I am using the CC compiler found in Solaris Studio 12.4 (CC: Sun C++ 5.13 SunOS_sparc 151845-14 2016/03/28)

Here are the compile flags that I am using for jsoncpp.cpp:

> CC -KPIC -m64  -std=c++11  -DSOLARIS -I. -I../src/include  -I../src/include/platforms/solaris_SPARC64  -I dist -c dist/jsoncpp.cpp -o dist/jsoncpp.o

I have built this project successfully (using Jsoncpp 1.6.5) on Suse Linux (GCC compiler), Red Hat (GCC), and Windows (Visual Studio) and it works fine, but for some reason the Solaris build using the CC compiler is throwing this error.  Any ideas?  Anything I'm missing?  Any more information I should include?

Thanks!

**Comment by cdunn2001** [comment] 2016-05-28 15:09
Could you tell us the version of the gcc compiler on Solaris? (`gcc --version`)

This seems similar to #411, where we managed to find a fix. If you could propose a fix, that would help. What we are doing is necessary for binary-compatibility and not a bug, but we have trouble explaining that to compilers.

**Comment by punchkicker** [comment] 2016-05-30 21:36
I am actually not using the gcc compiler on Solaris, but the CC compiler.  It is version Sun C++ 5.13 SunOS_sparc 151845-14 2016/03/28, and is included in Solaris Studio 12.4.   Is jsoncpp only compatible with gcc?

**Comment by cdunn2001** [comment] 2016-05-30 22:11
We definitely want compatibility with as many compilers as possible, but we don't test on Solaris. If you can find a fix, please let us know. Otherwise, for the sake of binary-compatibility, this cannot be fixed cleanly until 2.0.

**Comment by punchkicker** [comment] 2016-06-01 01:55
thanks for the info.  For the time being, I installed gcc 4.8 on my Solaris machine and it works fine now.  I'll look into why the cc compiler wasn't working when I get some time.

**Comment by BillyDonahue** [comment] 2018-05-28 21:27
old and apparently fixed. Closing.

**Closed by BillyDonahue** 2018-05-28 21:27 UTC
Labels: build
