### ISSUE TITLE
got a bunch of errors :P

### ISSUE THREAD

**Issue by bengris32** [open-source-parsers/jsoncpp#673] opened 2017-09-13 19:15 UTC
```cpp
external/jsoncpp/chromium-overrides/src/lib_json/json_value.cpp: At global scope:
external/jsoncpp/chromium-overrides/src/lib_json/json_value.cpp:1437:18: error: no 'bool Json::Value::isInt64() const' member function declared in class 'Json::Value'
 Value::isInt64() const
                  ^
external/jsoncpp/chromium-overrides/src/lib_json/json_value.cpp:1461:19: error: no 'bool Json::Value::isUInt64() const' member function declared in class 'Json::Value'
 Value::isUInt64() const
                   ^
external/jsoncpp/chromium-overrides/src/lib_json/json_value.cpp: In member function 'bool Json::Value::isIntegral() const':
external/jsoncpp/chromium-overrides/src/lib_json/json_value.cpp:1489:18: error: 'isInt64' was not declared in this scope
   return isInt64() || isUInt64();
                  ^
external/jsoncpp/chromium-overrides/src/lib_json/json_value.cpp:1489:32: error: 'isUInt64' was not declared in this scope
   return isInt64() || isUInt64();
                                ^
external/jsoncpp/chromium-overrides/src/lib_json/json_value.cpp: At global scope:
external/jsoncpp/chromium-overrides/src/lib_json/json_value.cpp:1813:1: warning: unused parameter 'path' [-Wunused-parameter]
 Path::addPathInArg( const std::string &path, 
 ^
external/jsoncpp/chromium-overrides/src/lib_json/json_value.cpp:1834:1: warning: unused parameter 'path' [-Wunused-parameter]
 Path::invalidPath( const std::string &path, 
 ^
external/jsoncpp/chromium-overrides/src/lib_json/json_value.cpp:1834:1: warning: unused parameter 'location' [-Wunused-parameter]
external/jsoncpp/chromium-overrides/src/lib_json/json_value.cpp: In member function 'std::string Json::Value::asString() const':
external/jsoncpp/chromium-overrides/src/lib_json/json_value.cpp:725:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
external/jsoncpp/chromium-overrides/src/lib_json/json_value.cpp: In member function 'Json::Value::Int Json::Value::asInt() const':
external/jsoncpp/chromium-overrides/src/lib_json/json_value.cpp:758:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
external/jsoncpp/chromium-overrides/src/lib_json/json_value.cpp: In member function 'Json::Value::UInt Json::Value::asUInt() const':
external/jsoncpp/chromium-overrides/src/lib_json/json_value.cpp:783:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
external/jsoncpp/chromium-overrides/src/lib_json/json_value.cpp: In member function 'Json::Value::Int64 Json::Value::asInt64() const':
external/jsoncpp/chromium-overrides/src/lib_json/json_value.cpp:809:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
external/jsoncpp/chromium-overrides/src/lib_json/json_value.cpp: In member function 'Json::Value::UInt64 Json::Value::asUInt64() const':
external/jsoncpp/chromium-overrides/src/lib_json/json_value.cpp:833:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
external/jsoncpp/chromium-overrides/src/lib_json/json_value.cpp: In member function 'double Json::Value::asDouble() const':
external/jsoncpp/chromium-overrides/src/lib_json/json_value.cpp:882:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
external/jsoncpp/chromium-overrides/src/lib_json/json_value.cpp: In member function 'float Json::Value::asFloat() const':
external/jsoncpp/chromium-overrides/src/lib_json/json_value.cpp:907:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
external/jsoncpp/chromium-overrides/src/lib_json/json_value.cpp: In member function 'bool Json::Value::asBool() const':
external/jsoncpp/chromium-overrides/src/lib_json/json_value.cpp:928:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
external/jsoncpp/chromium-overrides/src/lib_json/json_value.cpp: In member function 'bool Json::Value::isIntegral() const':
external/jsoncpp/chromium-overrides/src/lib_json/json_value.cpp:1493:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
cc1plus: some warnings being treated as errors
```

**Comment by cdunn2001** [comment] 2017-09-13 23:43
Could this be caused by the warning push/pop we just added? If you figure anything out, please let us know.

**Comment by bengris32** [comment] 2017-10-06 16:20
Sorry for late reply :P,This time round, I have got ALLOT less errors than before(btw android uses jsoncpp, and im compiling android 5.1)
Here are the errors:
external/jsoncpp/chromium-overrides/src/lib_json/json_value.cpp:32:21: error: conflicting declaration 'const Json::Value& Json::Value::null'
 const Value& Value::null = reinterpret_cast<const Value&>(kNull);
                     ^
In file included from external/jsoncpp/chromium-overrides/src/lib_json/json_value.cpp:8:0:
external/jsoncpp/include/json/value.h:139:26: error: 'Json::Value::null' has a previous declaration as 'const Json::Value Json::Value::null'
       static const Value null;
                          ^
external/jsoncpp/chromium-overrides/src/lib_json/json_value.cpp:32:21: error: declaration of 'const Json::Value Json::Value::null' outside of class is not definition [-fpermissive]
 const Value& Value::null = reinterpret_cast<const Value&>(kNull);
                     ^
external/jsoncpp/chromium-overrides/src/lib_json/json_value.cpp:32:64: error: 'Json::Value::null' cannot be initialized by a non-constant expression when being declared
 const Value& Value::null = reinterpret_cast<const Value&>(kNull);
                                                                ^
external/jsoncpp/chromium-overrides/src/lib_json/json_value.cpp: In copy constructor 'Json::Value::CZString::CZString(const Json::Value::CZString&)':
external/jsoncpp/chromium-overrides/src/lib_json/json_value.cpp:198:34: warning: enumeral and non-enumeral type in conditional expression [enabled by default]
                          : other.index_ )
                                  ^
external/jsoncpp/chromium-overrides/src/lib_json/json_value.cpp: At global scope:
external/jsoncpp/chromium-overrides/src/lib_json/json_value.cpp:1809:1: warning: unused parameter 'path' [-Wunused-parameter]
 Path::addPathInArg( const std::string &path, 
 ^
external/jsoncpp/chromium-overrides/src/lib_json/json_value.cpp:1830:1: warning: unused parameter 'path' [-Wunused-parameter]
 Path::invalidPath( const std::string &path, 
 ^
external/jsoncpp/chromium-overrides/src/lib_json/json_value.cpp:1830:1: warning: unused parameter 'location' [-Wunused-parameter]
make: *** [/home/ben/WORKING_DIRECTORY/out/target/product/j2lte/obj/STATIC_LIBRARIES/libjsoncpp_intermediates/chromium-overrides/src/lib_json/json_value.o] Error 1
make: *** Waiting for unfinished jobs....

#### make failed to build some targets (17:45 (mm:ss)) ####

**Comment by cdunn2001** [comment] 2017-10-07 05:40
I have no ideas. Maybe there is a problem with the amalgamate.py script, if you are using that. But whatever the problem is, you'll have to solve it yourself, and then tell us what you need changed.

**Comment by bengris32** [comment] 2017-10-08 11:32
I have reduced all the errors to just ONE error
here it is:
external/jsoncpp/chromium-overrides/src/lib_json/json_value.cpp:32:27: error: the address of 'Json::kNull' will always evaluate as 'true' [-Werror=address]
 static const Value null = kNull;

**Comment by cdunn2001** [comment] 2017-10-10 00:54
Oh, that's a known problem. We spent a lot of combined dev-hours solving that a couple years ago.

I wonder what commit or release-tag you are using. I'm pretty sure you will not see that problem on `master`, nor in any `1.y.z` release. In fact, I think it's even fixed on the latest `0.y.z`. I have to go way back in the code history to find that line of code.

Please re-open if you are certain this is a recent problem and you can provide more information about version of source-code you are using.

**Closed by cdunn2001** 2017-10-10 00:54 UTC
Labels: bug, help wanted
